document.addEventListener('DOMContentLoaded',()=>{
  const P=Portfolio,icon=P.icon,esc=P.escape;
  const bar=document.querySelector('.mac-menubar'),popover=document.getElementById('system-popover'),spotlight=document.getElementById('spotlight-panel');
  let active=document.getElementById('win-parametres'),openMenu=null,anchor=null,hiddenWindows=[];
  const names=[['finder','Finder'],['editor','Word'],['email','Mail'],['terminal','Terminal'],['Vscode','Visual Studio Code'],['parametres','Réglages Système'],['safari','Safari'],['note','Notes'],['calculator','Calculatrice'],['maps','Plans']];
  const appName=win=>win?.dataset.appName||names.find(([cls])=>win?.classList.contains(cls))?.[1]||'Finder';
  function setActive(win){if(!win)return;active=win;bar.querySelector('.current-app').textContent=appName(win);}
  document.addEventListener('portfolio:active',e=>setActive(e.detail));
  document.addEventListener('pointerdown',e=>{const win=e.target.closest('.window');if(win)setActive(win);});
  document.addEventListener('portfolio:windowchange',()=>{const visible=[...document.querySelectorAll('.window')].filter(w=>getComputedStyle(w).display!=='none').sort((a,b)=>Number(b.style.zIndex)-Number(a.style.zIndex));setActive(visible[0]);});
  const actions={
    about:()=>{P.open('settings');P.showSettings('about');},settings:()=>P.open('settings'),welcome:()=>{P.open('settings');P.showSettings('welcome');},shortcuts:()=>{P.open('settings');P.showSettings('shortcuts');},
    projects:()=>P.open('finder'),compose:()=>{P.open('mail');P.composeMail();},terminal:()=>P.open('terminal'),spotlight:()=>showSpotlight(),
    close:()=>active?.querySelector('.window__taskbar--actions button:first-child')?.click(),minimize:()=>active?.querySelector('.window__taskbar--actions button:nth-child(2)')?.click(),maximize:()=>active?.querySelector('.window__taskbar--actions button:nth-child(3)')?.click(),
    save:()=>document.getElementById('word-save').click(),undo:()=>P.wordCommand('undo'),redo:()=>P.wordCommand('redo'),selectall:()=>{if(active?.classList.contains('editor')){const range=document.createRange();range.selectNodeContents(active.querySelector('.editor-area'));const selection=getSelection();selection.removeAllRanges();selection.addRange(range);}},
    desktop:()=>{if(hiddenWindows.length){hiddenWindows.forEach(([w,d])=>w.style.display=d);hiddenWindows=[];}else{hiddenWindows=[...document.querySelectorAll('.window')].filter(w=>getComputedStyle(w).display!=='none').map(w=>[w,w.style.display]);hiddenWindows.forEach(([w])=>w.style.display='none');}},
    appearance:()=>{P.open('settings');P.showSettings('appearance');},focus:()=>{const enabled=document.body.classList.toggle('desktop-focus');P.toast(enabled?'Concentration activée : le Dock est masqué.':'Concentration désactivée.');},
    motion:()=>{document.body.classList.toggle('reduce-motion');P.toast(document.body.classList.contains('reduce-motion')?'Animations réduites.':'Animations réactivées.');}
  };
  P.toast=text=>{document.querySelector('.desktop-toast')?.remove();const el=document.createElement('div');el.className='desktop-toast';el.setAttribute('role','status');el.textContent=text;document.body.append(el);setTimeout(()=>el.remove(),4500);};
  P.setBrightness=value=>document.getElementById('screen-dimmer').style.opacity=String(1-Number(value)/100);
  function item(label,action,key='',disabled=false){return `<button type="button" role="menuitem" class="menu-item" data-menu-action="${action}" ${disabled?'disabled':''}><span>${label}</span><kbd>${key}</kbd></button>`;}
  function menuHTML(menu){
    if(menu==='apple')return item('À propos de ce portfolio','about')+'<hr>'+item('Réglages Système…','settings')+item('Découvrir les applications','welcome')+'<hr>'+item(hiddenWindows.length?'Afficher les fenêtres':'Afficher le bureau','desktop')+item('Apparence du bureau…','appearance');
    if(menu==='application')return item('À propos de '+esc(appName(active)),'about')+item('Réglages…','settings')+'<hr>'+item('Masquer '+esc(appName(active)),'minimize','⌘ M')+item('Fermer la fenêtre','close','⌘ W');
    if(menu==='file')return item('Ouvrir un projet…','projects')+item('Nouveau message','compose')+item('Ouvrir Terminal','terminal')+'<hr>'+item('Télécharger le document','save','',!active?.classList.contains('editor'))+item('Fermer la fenêtre','close','⌘ W');
    if(menu==='edit')return item('Annuler','undo','⌘ Z',!active?.classList.contains('editor'))+item('Rétablir','redo','⇧ ⌘ Z',!active?.classList.contains('editor'))+'<hr>'+item('Tout sélectionner','selectall','⌘ A',!active?.classList.contains('editor'))+item('Rechercher…','spotlight','⌘ Espace');
    if(menu==='view')return item('Agrandir / restaurer','maximize')+item(hiddenWindows.length?'Afficher les fenêtres':'Afficher le bureau','desktop')+'<hr>'+item('Personnaliser le bureau…','appearance')+item('Réduire les animations','motion');
    if(menu==='window')return item('Réduire','minimize','⌘ M')+item('Agrandir / restaurer','maximize')+'<hr>'+names.filter(([cls])=>document.querySelector('.window.'+cls)).map(([cls,name])=>item(name,'window:'+cls)).join('');
    if(menu==='help')return item('Bienvenue sur le bureau de Noa','welcome')+item('Raccourcis clavier','shortcuts')+item('Explorer avec Terminal','terminal')+item('Contacter Noa','compose');
    if(menu==='wifi')return '<h3 class="popover-heading">Réseau</h3><p class="popover-detail">'+(navigator.onLine?'Le navigateur est connecté à Internet.':'Le navigateur est hors ligne.')+'</p><hr>'+item('À propos de ce bureau','about');
    if(menu==='battery')return '<h3 class="popover-heading">Batterie</h3><p class="popover-detail" id="battery-detail">Informations système non disponibles dans ce navigateur.</p><hr>'+item('Réglages du bureau…','appearance');
    if(menu==='control')return `<div class="control-grid"><button class="control-tile" type="button" data-panel="wifi"><span class="control-round">${icon('wifi')}</span><span>Réseau<small>${navigator.onLine?'Connecté':'Hors ligne'}</small></span></button><button type="button" class="control-tile ${document.body.classList.contains('desktop-focus')?'focus-on':''}" data-menu-action="focus">${icon('moon.fill')}<span>Concentration<small>${document.body.classList.contains('desktop-focus')?'Activée':'Désactivée'}</small></span></button><section class="control-tile control-wide"><strong>Luminosité du bureau</strong><label>${icon('sun.max')}<input id="control-brightness" aria-label="Luminosité du bureau" type="range" min="35" max="100" value="${Math.round((1-Number(document.getElementById('screen-dimmer').style.opacity||0))*100)}"></label></section><button class="control-tile" data-menu-action="motion">${icon('rectangle.on.rectangle')}<span>Animations<small>${document.body.classList.contains('reduce-motion')?'Réduites':'Activées'}</small></span></button><button class="control-tile" data-menu-action="appearance">${icon('gearshape')}<span>Réglages<small>Personnaliser</small></span></button></div>`;
    if(menu==='calendar'){const now=new Date(),year=now.getFullYear(),month=now.getMonth(),first=(new Date(year,month,1).getDay()+6)%7,days=new Date(year,month+1,0).getDate();return `<h3 class="calendar-title">${now.toLocaleDateString('fr-FR',{month:'long',year:'numeric'})}</h3><div class="calendar-grid">${['L','M','M','J','V','S','D'].map(d=>`<span class="day-name">${d}</span>`).join('')}${'<span></span>'.repeat(first)}${Array.from({length:days},(_,i)=>`<span class="${i+1===now.getDate()?'today':''}">${i+1}</span>`).join('')}</div>`;}
    return '';
  }
  function closeMenu(returnFocus=false){popover.hidden=true;openMenu=null;bar.querySelectorAll('[data-system-menu]').forEach(b=>b.setAttribute('aria-expanded','false'));if(returnFocus)anchor?.focus();}
  function showMenu(menu,button){openMenu=menu;anchor=button;popover.dataset.panel=menu;spotlight.hidden=true;popover.innerHTML=menuHTML(menu);popover.hidden=false;popover.setAttribute('role',['control','calendar','battery','wifi'].includes(menu)?'dialog':'menu');bar.querySelectorAll('[data-system-menu]').forEach(b=>b.setAttribute('aria-expanded',String(b===button)));const rect=button.getBoundingClientRect();popover.style.top='32px';popover.style.left=Math.max(7,Math.min(rect.left,innerWidth-popover.offsetWidth-8))+'px';popover.querySelector('#control-brightness')?.addEventListener('input',e=>P.setBrightness(e.target.value));if(menu==='battery'&&navigator.getBattery)navigator.getBattery().then(b=>{const text=document.getElementById('battery-detail');if(text)text.textContent=`${Math.round(b.level*100)} % · ${b.charging?'En charge':'Sur batterie'}`;}).catch(()=>{});}
  bar.querySelectorAll('[data-system-menu]').forEach(button=>{button.addEventListener('click',()=>openMenu===button.dataset.systemMenu?closeMenu():showMenu(button.dataset.systemMenu,button));button.addEventListener('mouseenter',()=>{if(openMenu)showMenu(button.dataset.systemMenu,button);});button.addEventListener('keydown',e=>{if(e.key==='ArrowDown'){e.preventDefault();showMenu(button.dataset.systemMenu,button);popover.querySelector('button:not(:disabled)')?.focus();}});});
  popover.addEventListener('click',e=>{const panel=e.target.closest('[data-panel]');if(panel){showMenu(panel.dataset.panel,anchor);return;}const control=e.target.closest('[data-menu-action]');if(!control||control.disabled)return;const action=control.dataset.menuAction;closeMenu();if(action.startsWith('window:')){const cls=action.slice(7),lookup={finder:'finder',editor:'word',email:'mail',terminal:'terminal',Vscode:'code',parametres:'settings',safari:'safari',note:'notes',calculator:'calc',maps:'maps'};if(lookup[cls]==='calc')document.querySelector('.open-cal').click();else if(cls==='maps')document.querySelector('.open-map')?.click();else P.open(lookup[cls]);}else actions[action]?.();});
  popover.addEventListener('keydown',e=>{const controls=[...popover.querySelectorAll('button:not(:disabled),input')];let index=controls.indexOf(document.activeElement);if(['ArrowDown','ArrowUp'].includes(e.key)){e.preventDefault();controls[(index+(e.key==='ArrowDown'?1:-1)+controls.length)%controls.length]?.focus();}});
  document.addEventListener('pointerdown',e=>{if(!popover.contains(e.target)&&!bar.contains(e.target))closeMenu();if(!spotlight.contains(e.target)&&!e.target.closest('#spotlight-toggle'))spotlight.hidden=true;});
  function spotlightEntries(){return [['finder','Finder','Mes projets','icon/dock/finder.png'],['word','Word','Documents','icon/wordicone.png'],['mail','Mail','Écrire à Noa','icon/dock/mail.png'],['code','Visual Studio Code','Compétences','icon/dock/vscode.svg'],['terminal','Terminal','Explorer en ligne de commande','icon/dock/terminal.png'],['settings','Réglages Système','Bienvenue','icon/dock/preferences.png'],['safari','Safari','Mon histoire & CV','icon/Launchpad/safari.png'],['notes','Notes','Mon parcours','icon/dock/notes.png']].map(([id,name,detail,img])=>({id,name,detail,img})).concat(P.projects.map(p=>({id:'project:'+p.id,name:p.name,detail:p.category,img:'icon/apple/'+p.folder+'.png'})));}
  const search=spotlight.querySelector('input');function renderSearch(){const q=search.value.toLocaleLowerCase();const results=spotlightEntries().filter(x=>(x.name+x.detail).toLocaleLowerCase().includes(q));document.getElementById('spotlight-results').innerHTML=results.map(e=>`<button type="button" data-result="${e.id}"><img src="${e.img}" alt=""><span>${esc(e.name)}</span><small>${esc(e.detail)}</small></button>`).join('')||'<p class="popover-detail">Aucun résultat.</p>';}
  function showSpotlight(){closeMenu();spotlight.hidden=false;search.value='';renderSearch();search.focus();}
  document.getElementById('spotlight-toggle').addEventListener('click',()=>spotlight.hidden?showSpotlight():spotlight.hidden=true);search.addEventListener('input',renderSearch);
  spotlight.addEventListener('click',e=>{const b=e.target.closest('[data-result]');if(!b)return;spotlight.hidden=true;b.dataset.result.startsWith('project:')?P.openDocument(b.dataset.result.slice(8)):P.open(b.dataset.result);});
  spotlight.addEventListener('keydown',e=>{const results=[...spotlight.querySelectorAll('[data-result]')];if(e.key==='ArrowDown'){e.preventDefault();results[(results.indexOf(document.activeElement)+1)%results.length]?.focus();}if(e.key==='ArrowUp'){e.preventDefault();const i=results.indexOf(document.activeElement);i<=0?search.focus():results[i-1].focus();}if(e.key==='Enter'&&document.activeElement===search){e.preventDefault();results[0]?.click();}});
  document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeMenu(true);spotlight.hidden=true;}if((e.metaKey||e.ctrlKey)&&e.code==='Space'){e.preventDefault();showSpotlight();}});
  // Replace the old desktop context menu with functional desktop actions only.
  document.onclick=null;document.oncontextmenu=null;document.getElementById('contextMenu').hidden=true;
  document.addEventListener('contextmenu',e=>{if(e.target.closest('.window,input,textarea,[contenteditable],.mac-menubar,.system-popover'))return;e.preventDefault();showMenu('apple',bar.querySelector('.apple-menu-button'));popover.style.left=Math.min(e.clientX,innerWidth-popover.offsetWidth-10)+'px';popover.style.top=Math.min(e.clientY,innerHeight-popover.offsetHeight-10)+'px';});
  setActive(active);
});
