document.addEventListener('DOMContentLoaded',()=>{
  const P=Portfolio,esc=P.escape,profile=P.profile;
  const content=document.getElementById('safari-page-content');let current='histoire',history=['histoire'],index=0;
  const card=(id,img,kind,text)=>{const p=P.projects.find(x=>x.id===id);return `<button class="blog-card" data-project="${id}"><div class="blog-card-img${img?'':' is-text'}">${img?`<img src="${img}" alt="${esc(p.name)}" loading="lazy">`:esc(p.name)}</div><div class="blog-card-body"><small>${kind}</small><strong>${esc(p.name)}</strong><span>${text}</span><div class="blog-card-more">Lire le projet →</div></div></button>`;};
  const story=`<article class="blog">
    <header class="blog-top"><div class="blog-wrap"><a class="blog-logo" href="#blog-top" aria-label="Haut de la page">NG</a><nav class="blog-links" aria-label="Navigation du blog"><a href="#story-code" class="is-current">Mon histoire</a><button data-open-projects>Mes projets</button><a href="#story-travel">Voyages</a><button data-safari-page="cv">Mon CV</button></nav><button class="blog-btn" data-contact>Me contacter</button></div></header>
    <section class="blog-hero" id="blog-top"><div class="blog-wrap"><span class="blog-eyebrow">Noa Giannone · Développeur · Marseille</span><h1>Entre les lignes de code<br><span class="blog-hl">et les lignes aériennes.</span></h1><div class="blog-hero-actions"><button class="blog-btn" data-open-projects>Voir mes projets</button><a class="blog-play" href="#story-code"><i>▶</i>Lire mon histoire</a></div></div></section>
    <section class="blog-intro"><div class="blog-wrap"><span class="blog-eyebrow">Bienvenue</span><p>Je m’appelle Noa Giannone, j’ai vingt ans, et le développement fait partie de ma vie depuis quatre ans. Le reste de ce portfolio montre ce que je fais ; cette page raconte plutôt qui je suis : ce qui m’a amené au code, les voyages qui m’ont marqué, et cette passion pour l’aviation qui n’a fait que grandir avec les années.</p>
      <div class="blog-badge"><svg viewBox="0 0 150 150" aria-hidden="true"><defs><path id="blog-badge-path" d="M75,75 m-60,0 a60,60 0 1,1 120,0 a60,60 0 1,1 -120,0"/></defs><text><textPath href="#blog-badge-path" textLength="372">Code · Voyages · Avions · Marseille ·</textPath></text></svg><img src="images/profile-noa.jpeg" alt="Noa Giannone"></div></div></section>
    <section class="blog-hello"><img src="images/profile-noa.jpeg" alt="Noa en voyage à Vienne" loading="lazy"><div><span class="blog-eyebrow">Hello !</span><h2>Moi, <span class="blog-hl">à Vienne</span></h2><p>Cette photo a été prise à Vienne, lors de mon premier voyage avec ma copine, et c’est un souvenir qui restera gravé. Nous y étions au moment de Noël, dans cette atmosphère si particulière des fêtes, et ces quelques jours ont été remplis de fous rires, de découvertes et de moments forts.</p><p>Ce voyage a été une véritable révélation. J’y ai découvert la beauté de voyager à deux : vivre des moments aussi intenses avec sa moitié, s’émerveiller ensemble devant les mêmes choses, et partager cette joie de tout découvrir. C’est là qu’est née notre frénésie de voyages, et depuis, nous n’avons jamais cessé de repartir.</p><p>Si je l’ai choisie, c’est aussi parce qu’elle en dit long sur moi. J’ai toujours eu envie de découvrir, d’expérimenter, de tester, de voir par moi-même et d’apprendre. C’est ce qui me pousse à partir vers une ville que je ne connais pas, et c’est exactement la même envie qui m’a fait écrire mes premières lignes de code.</p><p>Et quand j’ai besoin de souffler, je file dans les collines, à VTT ou en courant. Ces moments en plein air me libèrent l’esprit entre deux sessions de travail, et j’en reviens toujours avec les idées plus claires.</p><button class="blog-btn is-outline" data-safari-page="cv">Voir mon parcours</button></div></section>
    <section class="blog-chapter" id="story-code"><div class="blog-wrap"><span class="blog-eyebrow">01 · Le code</span><h2>Comment tout <span class="blog-hl">a commencé</span></h2>
      <p>Tout a commencé grâce à mon oncle, développeur de métier. En me montrant ce sur quoi il travaillait, il m’a surtout ouvert les yeux sur l’étendue de ce que permet l’informatique : la possibilité de créer, de donner forme à une idée et de la voir exister sans dépendre de qui que ce soit. J’étais déjà attiré par l’électronique et je passais de longues heures sur mon ordinateur : ça a été un vrai déclic.</p>
      <p>J’ai écrit mes premières lignes de code à seize ans, en suivant, comme beaucoup, les cours d’OpenClassrooms. Le HTML et le CSS d’abord, puis, par curiosité, d’autres langages et d’autres technologies. Pendant des mois, j’ai créé de petits sites sur mon temps libre, le soir ou le week-end, en tâtonnant, simplement pour le plaisir d’apprendre et de comprendre comment les choses fonctionnaient.</p>
      <p>Petit à petit, cette passion est devenue une évidence. J’ai choisi d’intégrer une école d’informatique pour en faire mon métier, et je suis aujourd’hui développeur en alternance. Au quotidien, je touche à des domaines très variés, du développement de firmwares en C et en C++ pour des capteurs jusqu’au back-end, en passant par Python, le front-end, le DevOps et l’administration de serveurs, avec une préférence pour la création d’applications.</p>
      <p>Parallèlement, j’ai fondé il y a un peu plus de deux ans mon auto-entreprise, un studio de création d’applications qui me permet de mener deux activités complémentaires. D’un côté, je réalise des projets pour des clients aussi divers que la mairie de Toulon, une agence événementielle toulonnaise, une conciergerie familiale de La Ciotat ou des entreprises étrangères spécialisées dans l’intelligence artificielle. De l’autre, je développe mes propres applications, comme Whisp et Vago.</p>
      <p>S’il y a un point commun entre tous ces projets, c’est l’envie d’être utile. Je n’ai jamais eu envie de créer des outils uniquement pour la technique. Les projets qui me motivent vraiment partent d’un problème concret, souvent un problème que j’ai moi-même rencontré, et doivent apporter une vraie réponse à celles et ceux qui les utilisent.</p></div></section>
    <section class="blog-projects"><div class="blog-wrap"><h2>Mes projets</h2><p>Voici une sélection de projets menés pour des clients ou portés par mon studio. Chacun est né d’un besoin précis, et chaque fiche raconte son contexte, ce que j’ai réalisé et ce que j’en ai appris.</p>
      <div class="blog-cards">${card('lieux','images/projects/fornap-agenda.png','Tiers-lieu culturel','Plateforme publique et logiciel de gestion d’un tiers-lieu culturel installé au Fort Napoléon.')}${card('vago','images/projects/vago-cadeaux.png','App mobile','Un jeu mobile multijoueur qui convertit le temps de jeu en litres de carburant.')}${card('whisp','','App mobile','Ma première application publiée, imaginée pour rapprocher les étudiants d’un même campus.')}${card('fete','images/projects/fete-mobile.png','Site événementiel','Le site de la Fête de la musique à Toulon, conçu pour la mairie.')}</div></div></section>
    <section class="blog-chapter" id="story-travel"><div class="blog-wrap"><span class="blog-eyebrow">02 · Le voyage</span><h2>Le goût <span class="blog-hl">de l’ailleurs</span></h2>
      <p>Mon goût pour le voyage, je le dois à mes parents. C’est avec eux que j’ai découvert la côte Ouest des États-Unis puis le Canada. Ces voyages m’ont profondément marqué : c’est là que j’ai compris à quel point le monde était immense, et à quel point j’en connaissais peu.</p>
      <p>Dès le lendemain de mes dix-huit ans, je suis parti pour mon premier voyage en solo. Ce que je recherche avant tout, c’est cette liberté qu’on ressent en voyage : choisir où aller, construire son itinéraire selon ses envies, découvrir une culture qui n’est pas la sienne. Et, je l’avoue, goûter la cuisine locale, mon petit plaisir coupable.</p>
      <p>Depuis, je suis allé à Malte, en Croatie, à Chypre, où les activités nautiques ont rythmé mon séjour, ou encore à Budapest, dont l’effervescence et l’ambiance d’Europe de l’Est m’ont fait découvrir une culture très différente de la nôtre.</p>
      <p>Vienne occupe toutefois une place à part. C’est là que j’ai fait mon premier voyage avec ma copine, et j’en garde un souvenir inoubliable. La ville a quelque chose de féerique : il s’y passe énormément de choses, et pourtant elle reste étonnamment calme. Elle est magnifique, et elle l’était encore plus avec les marchés de Noël, que j’adore.</p></div>
      <div class="blog-gallery"><figure><img src="images/newyork.jpg" alt="New York" loading="lazy"><figcaption>New York</figcaption></figure><figure><img src="images/vienne.jpg" alt="Vienne" loading="lazy"><figcaption>Vienne</figcaption></figure><figure><img src="images/dubrovnik.jpg" alt="Dubrovnik" loading="lazy"><figcaption>Dubrovnik</figcaption></figure></div>
      <div class="blog-wrap" style="max-width:860px"><div class="blog-countries"><span>Déjà visités :</span><b>États-Unis</b><b>Canada</b><b>Malte</b><b>Croatie</b><b>Autriche</b><b>Hongrie</b><b>Chypre</b><b>Portugal</b><b>Espagne</b></div></div></section>
    <section class="blog-airport"><div class="blog-wrap"><span class="blog-eyebrow">03 · Les avions</span><h2>Une fascination <span class="blog-hl">pour l’aviation</span></h2>
      <p>Tous ceux qui me connaissent pourraient en témoigner : l’aviation occupe une grande place dans ma vie. Longtemps, j’ai cru que mon attachement aux aéroports tenait simplement à ce qu’ils représentent, le point de départ des vacances et cette excitation si particulière qui précède chaque voyage. Ces dernières années, j’ai compris que c’était bien plus que ça.</p>
      <p>J’aime l’aéroport pour ce qu’il est en lui-même : un lieu toujours en effervescence, un peu hors du temps. Il suffit de lever les yeux vers le tableau des départs pour s’en rendre compte. Certains partent, d’autres reviennent ; on se presse, on attend, on se retrouve. Chacun y arrive avec sa propre histoire, et toutes ces histoires s’écrivent au même instant, au même endroit. Pour moi, un aéroport est une petite société à part entière, un condensé du monde.</p>
      <p>Les avions me fascinent tout autant. Leur taille, d’abord, mais surtout ce qu’ils représentent : un véritable exploit humain, devenu si banal qu’on en oublie la prouesse. Ma copine l’a bien compris en m’offrant la visite des chaînes d’assemblage d’Airbus et du musée de l’aviation, et je me suis régalé.</p>
      <p>Près de Marignane, il y a un très bon spot pour observer les avions, et j’y passe régulièrement mes soirées avec ma copine. J’ai même bricolé une antenne pour capter les signaux ADS-B des appareils et d’écouter les communications avec la tour de contrôle. Il m’arrive aussi de m’installer à l’aéroport, ordinateur ouvert, pour y travailler une journée entière, simplement parce que c’est un lieu où je me sens bien.</p>
      <div class="blog-next"><i>✈</i><div><span>Prochain départ</span><strong>Bientôt, j’espère !</strong></div></div></div></section>
    <footer class="blog-footer"><div class="blog-wrap"><span class="blog-eyebrow">Me contacter</span><h2>Écrivez-<span class="blog-hl">moi</span></h2><p class="blog-footer-text">Pour un projet, une question ou une collaboration, je serai ravi d’en discuter avec vous.</p><button class="blog-btn" data-contact>M’écrire</button><small>Noa Giannone · Marseille · Toulon</small></div></footer></article>`;
  // The supplied PDF is the source of truth. Display its exact raster preview
  // consistently, independently of browser PDF plug-ins; link to the tagged PDF.
  const cvURL = 'documents/CV-Noa-Giannone.pdf';
  const cvPreview = `<a class="cv-pdf-preview" href="${cvURL}" target="_blank" rel="noopener" aria-label="Ouvrir le CV original en PDF pour le lire et zoomer"><img src="documents/CV-Noa-Giannone-preview.png" width="1415" height="2000" alt="Aperçu du CV de Noa Giannone — ouvrir le PDF pour lire le document et zoomer"></a>`;
  function cvHTML() {
    return `<section class="cv-pdf-viewer" aria-label="CV de Noa Giannone">
      <div class="cv-browser-toolbar"><span>CV — Noa Giannone</span><div class="cv-pdf-actions"><a href="${cvURL}" target="_blank" rel="noopener">Ouvrir le PDF ↗</a><a href="${cvURL}" download>Télécharger ${P.icon('square.and.arrow.down')}</a></div></div>
      ${cvPreview}
    </section>`;
  }
  function homeHTML(){return `<section class="safari-start"><h1>Favoris</h1><div class="safari-favorites"><button data-safari-page="histoire"><img src="images/profile-noa.jpeg" alt="">Mon histoire</button><button data-safari-page="cv"><img src="icon/apple/DocumentsFolderIcon.png" alt="">Mon CV</button><button data-open-projects><img src="icon/dock/finder.png" alt="">Mes projets</button><button data-contact><img src="icon/dock/mail.png" alt="">Me contacter</button></div><h2>À découvrir</h2><div class="safari-reading-list"><button data-safari-page="histoire"><img src="images/newyork.jpg" alt="New York"><span>Mon histoire<strong>Entre le code, le voyage et l’aviation.</strong><small>D’où je viens et ce qui me plaît.</small></span></button><button data-safari-page="cv"><img src="images/profile-noa.jpeg" alt="Noa"><span>Mon parcours<strong>Du front-end aux objets connectés.</strong><small>Expériences, compétences et projets.</small></span></button></div></section>`;}
  function render(){content.innerHTML=current==='histoire'?story:current==='cv'?cvHTML():homeHTML();document.querySelectorAll('[data-safari-page]').forEach(b=>{b.classList.toggle('selected',b.dataset.safariPage===current);if(b.getAttribute('role')==='tab')b.setAttribute('aria-selected',String(b.dataset.safariPage===current));});document.getElementById('safari-address').value=current==='home'?'Page de démarrage':`noagiannone.fr/${current==='cv'?'cv':'mon-histoire'}`;document.getElementById('safari-back').disabled=index===0;document.getElementById('safari-forward').disabled=index===history.length-1;content.scrollTop=0;}
  content.addEventListener('scroll',()=>content.querySelector('.blog-top')?.classList.toggle('is-solid',content.scrollTop>40),{passive:true});
  P.safariNavigate=page=>{if(!['home','histoire','cv'].includes(page)||page===current)return;history=history.slice(0,index+1);history.push(page);index++;current=page;render();};
  document.getElementById('win-safari').addEventListener('click',e=>{const tab=e.target.closest('[data-safari-page]');if(tab)P.safariNavigate(tab.dataset.safariPage);if(e.target.closest('[data-contact]')){P.open('mail');P.composeMail();}if(e.target.closest('[data-open-projects]'))P.open('finder');const project=e.target.closest('[data-project]');if(project)P.openDocument(project.dataset.project);const jump=e.target.closest('#safari-page-content a[href^="#"]');if(jump){e.preventDefault();content.querySelector(jump.getAttribute('href'))?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'auto':'smooth'});}});
  document.getElementById('safari-back').addEventListener('click',()=>{if(index>0){current=history[--index];render();}});document.getElementById('safari-forward').addEventListener('click',()=>{if(index<history.length-1){current=history[++index];render();}});document.getElementById('safari-refresh').addEventListener('click',render);
  document.getElementById('safari-sidebar-toggle').addEventListener('click',e=>{const sidebar=document.querySelector('.safari-native-sidebar');sidebar.hidden=!sidebar.hidden;e.currentTarget.setAttribute('aria-expanded',String(!sidebar.hidden));});
  document.getElementById('safari-address').addEventListener('keydown',e=>{if(e.key!=='Enter')return;const q=e.target.value.toLocaleLowerCase();if(/cv|parcours|compétence/.test(q))P.safariNavigate('cv');else if(/histoire|noa|moi/.test(q))P.safariNavigate('histoire');else if(/home|accueil|démarrage/.test(q))P.safariNavigate('home');else P.toast('Dans ce portfolio : recherchez « histoire », « CV » ou « accueil ».');});
  document.getElementById('safari-share').addEventListener('click',async()=>{const url=new URL(location.href);url.hash=current;try{await navigator.clipboard.writeText(url.href);P.toast('Lien copié.');}catch{P.toast('Copiez l’adresse depuis la barre de votre navigateur pour partager cette page.');}});
  if(['histoire','cv','home'].includes(location.hash.slice(1))){current=location.hash.slice(1);history=[current];}
  render();
  // Notes presents the detailed profile; downloads use the supplied original CV.
  const noteBody=document.querySelector('.note-body');
  if(noteBody){noteBody.innerHTML=`<h1>Mon parcours</h1><p class="notes-intro">${profile.title}</p><div class="note-section"><h2>Expériences professionnelles</h2>${profile.experiences.map(e=>`<div class="experience-block"><h3>${e.role}</h3><span class="company">${e.company} · ${e.location}</span><span class="date">${e.date}</span><ul>${e.points.map(t=>`<li>${esc(t)}</li>`).join('')}</ul></div>`).join('')}</div><div class="note-section"><h2>Compétences</h2>${profile.skills.map(s=>`<div class="experience-block"><h3>${s.name}</h3><p>${s.items.join(' · ')}</p></div>`).join('')}</div><div class="note-section"><h2>Formation</h2>${profile.education.map(e=>`<div class="education-block"><h3>${e.title}</h3><span class="school">${e.school}</span><span class="date">${e.date}</span><p>${e.text}</p></div>`).join('')}</div><a class="native-button" href="documents/CV-Noa-Giannone.pdf" download>Télécharger mon CV</a>`;}
  const noteItems=document.querySelectorAll('.notes-items-list > li');
  noteItems.forEach((item,i)=>{if(i===1){item.querySelector('.note-item-title').textContent='Mes compétences';const preview=item.querySelector('.note-preview-text');if(preview)preview.textContent='Front-end, mobile, firmware et réseau';}item.addEventListener('click',()=>{noteItems.forEach(n=>n.classList.toggle('active',n===item));const target=i===1?noteBody.querySelectorAll('.note-section')[1]:noteBody;target?.scrollIntoView({block:'start'});});});
  const meta=document.querySelector('.note-date');if(meta)meta.textContent='Parcours & compétences';
});
