document.addEventListener('DOMContentLoaded',()=>{
  const P=Portfolio,esc=P.escape,profile=P.profile;
  const content=document.getElementById('safari-page-content');let current='histoire',history=['histoire'],index=0;
  const card=(id,img,kind,text)=>{const p=P.projects.find(x=>x.id===id);return `<button class="blog-card" data-project="${id}"><div class="blog-card-img${img?'':' is-text'}">${img?`<img src="${img}" alt="${esc(p.name)}" loading="lazy">`:esc(p.name)}</div><div class="blog-card-body"><small>${kind}</small><strong>${esc(p.name)}</strong><span>${text}</span><div class="blog-card-more">Lire le projet →</div></div></button>`;};
  const story=`<article class="blog">
    <header class="blog-top"><div class="blog-wrap"><a class="blog-logo" href="#blog-top" aria-label="Haut de la page">NG</a><nav class="blog-links" aria-label="Navigation du blog"><a href="#story-code" class="is-current">Mon histoire</a><button data-open-projects>Mes projets</button><a href="#story-travel">Voyages</a><button data-safari-page="cv">Mon CV</button></nav><button class="blog-btn" data-contact>Me contacter</button></div></header>
    <section class="blog-hero" id="blog-top"><div class="blog-wrap"><span class="blog-eyebrow">Carnet de code &amp; de voyage</span><h1>Développeur à Marseille.<br><span class="blog-hl">Passionné de voyage.</span></h1><div class="blog-hero-actions"><button class="blog-btn" data-open-projects>Voir mes projets</button><a class="blog-play" href="#story-code"><i>▶</i>Lire mon histoire</a></div></div></section>
    <section class="blog-intro"><div class="blog-wrap"><span class="blog-eyebrow">Bienvenue</span><p>Développeur web et mobile basé à Marseille, je conçois des sites, des applications mobiles et des outils sur mesure, de l’interface jusqu’au serveur, et parfois jusqu’aux objets connectés. Cette page propose un regard plus personnel sur mon parcours : ce qui m’anime dans ce métier, ce que les voyages m’ont apporté, et l’origine de ma passion pour l’aviation.</p>
      <div class="blog-badge"><svg viewBox="0 0 150 150" aria-hidden="true"><defs><path id="blog-badge-path" d="M75,75 m-60,0 a60,60 0 1,1 120,0 a60,60 0 1,1 -120,0"/></defs><text><textPath href="#blog-badge-path" textLength="372">Développeur · Voyageur · Marseille ·</textPath></text></svg><img src="images/profile-noa.jpeg" alt="Noa Giannone"></div></div></section>
    <section class="blog-hello"><img src="images/profile-noa.jpeg" alt="Noa en voyage à Vienne" loading="lazy"><div><span class="blog-eyebrow">Hello !</span><h2>Moi c’est <span class="blog-hl">Noa</span></h2><p>Cette photo a été prise à Vienne, à la tombée du jour. Elle résume assez bien ma manière d’être : observer, chercher à comprendre le fonctionnement des choses et partir à la découverte de lieux inconnus. Devant un écran comme à l’autre bout du monde, c’est la même curiosité qui me guide.</p><button class="blog-btn is-outline" data-safari-page="cv">Voir mon parcours</button></div></section>
    <section class="blog-chapter" id="story-code"><div class="blog-wrap"><span class="blog-eyebrow">01 · Le code</span><h2>Ce qui me plaît <span class="blog-hl">dans ce métier</span></h2>
      <p>Ce qui m’attire avant tout dans l’informatique, c’est la liberté qu’elle offre. Elle permet de partir d’une idée, aussi modeste soit-elle, et de la concrétiser par soi-même, étape après étape. Voir prendre forme un outil qui, la veille encore, n’existait qu’à l’état de projet reste pour moi une source de satisfaction intacte.</p>
      <p>La technique n’est cependant pas une fin en soi. Ce qui me motive profondément, c’est l’utilité de ce que je conçois. Je ne cherche pas à créer des outils pour le seul plaisir de les créer : je souhaite qu’ils soient fiables, simples d’usage et qu’ils apportent une aide réelle à celles et ceux à qui ils s’adressent. C’est l’exigence que je m’efforce de tenir à chaque projet.</p>
      <p>La plupart de mes réalisations naissent d’une situation vécue ou observée. Whisp est issu de la difficulté à nouer des liens sur un campus universitaire de grande taille. Vago répond au poids croissant du carburant dans le budget des ménages. Avec FORNAP, j’ai eu l’occasion d’accompagner une équipe engagée dans la gestion d’un lieu culturel. Chaque fois, la démarche est identique : partir d’un besoin concret pour y apporter une réponse utile.</p></div></section>
    <section class="blog-projects"><div class="blog-wrap"><h2>Mes projets</h2><p>Une sélection de projets menés en mission pour des clients ou à titre personnel, chacun né d’un besoin concret. Sélectionnez une carte pour en découvrir le détail.</p>
      <div class="blog-cards">${card('lieux','images/projects/fornap-agenda.png','Tiers-lieu culturel','Site public, billetterie et back-office d’un tiers-lieu culturel à La Seyne-sur-Mer.')}${card('vago','images/projects/vago-cadeaux.png','App mobile','Application de micro-tasking qui convertit le temps passé sur mobile en cartes cadeaux carburant.')}${card('whisp','','App mobile','Messagerie de proximité favorisant les rencontres entre étudiants d’un même campus.')}${card('cyan','images/projects/cyan-dashboard.webp','Application IoT','Application de configuration et de suivi de capteurs de qualité de l’air.')}</div></div></section>
    <section class="blog-chapter" id="story-travel"><div class="blog-wrap"><span class="blog-eyebrow">02 · Le voyage</span><h2>Piqué du <span class="blog-hl">voyage</span></h2>
      <p>Le voyage constitue l’autre grande passion de ma vie, et je la dois à mes parents. C’est avec eux que j’ai découvert les États-Unis, le Canada et bien d’autres pays. Ces voyages m’ont profondément marqué : ils m’ont ouvert à d’autres cultures, à d’autres manières de vivre, et m’ont fait mesurer l’immensité du monde. Depuis, l’envie de le découvrir ne m’a plus quitté.</p>
      <p>En voyage, j’aime prendre le temps. Visiter, bien sûr, mais aussi flâner sans itinéraire précis, observer le quotidien des habitants et m’intéresser à leur culture. Ce sont souvent les instants imprévus qui laissent l’empreinte la plus durable : une perspective au détour d’une rue, une conversation, un lieu découvert par hasard.</p></div>
      <div class="blog-gallery"><figure><img src="images/newyork.jpg" alt="New York" loading="lazy"><figcaption>New York</figcaption></figure><figure><img src="images/vienne.jpg" alt="Vienne" loading="lazy"><figcaption>Vienne</figcaption></figure><figure><img src="images/dubrovnik.jpg" alt="Dubrovnik" loading="lazy"><figcaption>Dubrovnik</figcaption></figure></div>
      <div class="blog-wrap" style="max-width:860px"><div class="blog-countries"><span>Déjà visités :</span><b>États-Unis</b><b>Canada</b><b>Autriche</b><b>Croatie</b><b>Portugal</b><b>Espagne</b></div></div></section>
    <section class="blog-airport"><div class="blog-wrap"><span class="blog-eyebrow">03 · Les avions</span><h2>Une passion pour <span class="blog-hl">les avions</span></h2>
      <p>À cela s’ajoute une fascination pour l’aviation qui ne m’a jamais quitté. Je peux passer des heures à l’aéroport voisin de chez moi à observer les décollages et les atterrissages.</p>
      <p>Il m’arrive même d’y travailler, installé au Starbucks du terminal, l’ordinateur ouvert et les avions en toile de fond. J’apprécie profondément l’effervescence de ce lieu : les voyageurs qui partent en vacances, ceux qui rentrent chez eux, ceux qui pressent le pas pour ne pas manquer leur vol ou qui attendent un proche. Chacun y porte sa destination et son histoire.</p>
      <p>Un aéroport est un lieu où le monde entier se croise l’espace de quelques heures. J’y vois quelque chose de profondément beau.</p>
      <div class="blog-next"><i>✈</i><div><span>Prochain départ</span><strong>Bientôt, j’espère !</strong></div></div></div></section>
    <footer class="blog-footer"><div class="blog-wrap"><span class="blog-eyebrow">Me contacter</span><h2>On en <span class="blog-hl">discute</span> ?</h2><p class="blog-footer-text">Pour toute question, proposition de projet ou simple échange, n’hésitez pas à me contacter.</p><button class="blog-btn" data-contact>M’écrire</button><small>Noa Giannone · Marseille · Toulon</small></div></footer></article>`;
  P.cvHTML=()=>`<article class="cv-live"><header><div><span class="cv-overline">CURRICULUM VITÆ</span><h1>${profile.name}</h1><h2>${profile.title}</h2><p>${profile.location} · ${profile.email}</p></div><img src="images/profile-noa.jpeg" alt="Noa Giannone"></header><p class="cv-summary">Développeur passionné par le front-end et les applications iOS et Android. Je conçois des interfaces soignées et des plateformes sur mesure. Mon expérience s’étend aussi au firmware embarqué, aux données et aux infrastructures auto-hébergées.</p><div class="cv-columns"><main><h3>Expériences</h3>${profile.experiences.map(e=>`<section class="cv-experience"><div><h4>${e.role}</h4><span>${e.date}</span></div><h5>${e.company} · ${e.location}</h5><ul>${e.points.map(t=>`<li>${esc(t)}</li>`).join('')}</ul></section>`).join('')}<h3>Formation</h3>${profile.education.map(e=>`<section class="cv-experience"><div><h4>${e.title}</h4><span>${e.date}</span></div><h5>${e.school}</h5><p>${e.text}</p></section>`).join('')}</main><aside><h3>Compétences</h3>${profile.skills.map(s=>`<section><h4>${s.name}</h4><p>${s.items.join(' · ')}</p></section>`).join('')}<h3>Projets personnels</h3><p>Vago · Whisp · IA locale · ViteMonGrandOral</p><h3>Ce qui m’anime</h3><p>Créer des outils utiles.<br>Entreprendre et apprendre.<br>Voyager et découvrir l’aviation.</p></aside></div></article>`;
  function homeHTML(){return `<section class="safari-start"><h1>Favoris</h1><div class="safari-favorites"><button data-safari-page="histoire"><img src="images/profile-noa.jpeg" alt="">Mon histoire</button><button data-safari-page="cv"><img src="icon/apple/DocumentsFolderIcon.png" alt="">Mon CV</button><button data-open-projects><img src="icon/dock/finder.png" alt="">Mes projets</button><button data-contact><img src="icon/dock/mail.png" alt="">Me contacter</button></div><h2>À découvrir</h2><div class="safari-reading-list"><button data-safari-page="histoire"><img src="images/newyork.jpg" alt="New York"><span>En quelques mots<strong>Le code, le voyage et les avions.</strong><small>Qui je suis et ce qui me plaît.</small></span></button><button data-safari-page="cv"><img src="images/profile-noa.jpeg" alt="Noa"><span>Mon parcours<strong>Du front-end aux objets connectés.</strong><small>Expériences, compétences et projets.</small></span></button></div></section>`;}
  function render(){content.innerHTML=current==='histoire'?story:current==='cv'?`<div class="cv-browser-toolbar"><span>CV — Noa Giannone</span><a href="documents/CV-Noa-Giannone.pdf" download>Télécharger le PDF ${P.icon('square.and.arrow.down')}</a></div>${P.cvHTML()}`:homeHTML();document.querySelectorAll('[data-safari-page]').forEach(b=>{b.classList.toggle('selected',b.dataset.safariPage===current);if(b.getAttribute('role')==='tab')b.setAttribute('aria-selected',String(b.dataset.safariPage===current));});document.getElementById('safari-address').value=current==='home'?'Page de démarrage':`noagiannone.fr/${current==='cv'?'cv':'mon-histoire'}`;document.getElementById('safari-back').disabled=index===0;document.getElementById('safari-forward').disabled=index===history.length-1;content.scrollTop=0;}
  content.addEventListener('scroll',()=>content.querySelector('.blog-top')?.classList.toggle('is-solid',content.scrollTop>40),{passive:true});
  P.safariNavigate=page=>{if(!['home','histoire','cv'].includes(page)||page===current)return;history=history.slice(0,index+1);history.push(page);index++;current=page;render();};
  document.getElementById('win-safari').addEventListener('click',e=>{const tab=e.target.closest('[data-safari-page]');if(tab)P.safariNavigate(tab.dataset.safariPage);if(e.target.closest('[data-contact]')){P.open('mail');P.composeMail();}if(e.target.closest('[data-open-projects]'))P.open('finder');const project=e.target.closest('[data-project]');if(project)P.openDocument(project.dataset.project);const jump=e.target.closest('#safari-page-content a[href^="#"]');if(jump){e.preventDefault();content.querySelector(jump.getAttribute('href'))?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'auto':'smooth'});}});
  document.getElementById('safari-back').addEventListener('click',()=>{if(index>0){current=history[--index];render();}});document.getElementById('safari-forward').addEventListener('click',()=>{if(index<history.length-1){current=history[++index];render();}});document.getElementById('safari-refresh').addEventListener('click',render);
  document.getElementById('safari-sidebar-toggle').addEventListener('click',e=>{const sidebar=document.querySelector('.safari-native-sidebar');sidebar.hidden=!sidebar.hidden;e.currentTarget.setAttribute('aria-expanded',String(!sidebar.hidden));});
  document.getElementById('safari-address').addEventListener('keydown',e=>{if(e.key!=='Enter')return;const q=e.target.value.toLocaleLowerCase();if(/cv|parcours|compétence/.test(q))P.safariNavigate('cv');else if(/histoire|noa|moi/.test(q))P.safariNavigate('histoire');else if(/home|accueil|démarrage/.test(q))P.safariNavigate('home');else P.toast('Dans ce portfolio : recherchez « histoire », « CV » ou « accueil ».');});
  document.getElementById('safari-share').addEventListener('click',async()=>{const url=new URL(location.href);url.hash=current;try{await navigator.clipboard.writeText(url.href);P.toast('Lien copié.');}catch{P.toast('Copiez l’adresse depuis la barre de votre navigateur pour partager cette page.');}});
  if(['histoire','cv','home'].includes(location.hash.slice(1))){current=location.hash.slice(1);history=[current];}
  render();
  // The Notes CV and Safari CV consume the same profile so their content stays aligned.
  const noteBody=document.querySelector('.note-body');
  if(noteBody){noteBody.innerHTML=`<h1>Mon parcours</h1><p class="notes-intro">${profile.title}</p><div class="note-section"><h2>Expériences professionnelles</h2>${profile.experiences.map(e=>`<div class="experience-block"><h3>${e.role}</h3><span class="company">${e.company} · ${e.location}</span><span class="date">${e.date}</span><ul>${e.points.map(t=>`<li>${esc(t)}</li>`).join('')}</ul></div>`).join('')}</div><div class="note-section"><h2>Compétences</h2>${profile.skills.map(s=>`<div class="experience-block"><h3>${s.name}</h3><p>${s.items.join(' · ')}</p></div>`).join('')}</div><div class="note-section"><h2>Formation</h2>${profile.education.map(e=>`<div class="education-block"><h3>${e.title}</h3><span class="school">${e.school}</span><span class="date">${e.date}</span><p>${e.text}</p></div>`).join('')}</div><a class="native-button" href="documents/CV-Noa-Giannone.pdf" download>Télécharger mon CV</a>`;}
  const noteItems=document.querySelectorAll('.notes-items-list > li');
  noteItems.forEach((item,i)=>{if(i===1){item.querySelector('.note-item-title').textContent='Mes compétences';const preview=item.querySelector('.note-preview-text');if(preview)preview.textContent='Front-end, mobile, firmware et réseau';}item.addEventListener('click',()=>{noteItems.forEach(n=>n.classList.toggle('active',n===item));const target=i===1?noteBody.querySelectorAll('.note-section')[1]:noteBody;target?.scrollIntoView({block:'start'});});});
  const meta=document.querySelector('.note-date');if(meta)meta.textContent='Parcours & compétences';
});
