document.addEventListener('DOMContentLoaded',()=>{
  const P=Portfolio,esc=P.escape,profile=P.profile;
  const content=document.getElementById('safari-page-content');let current='histoire',history=['histoire'],index=0;
  const links=`<nav class="story-nav"><button data-safari-page="histoire">Noa Giannone<span>Développeur & créateur</span></button><div><button data-safari-page="cv">Mon parcours</button><button data-contact>Échangeons ${P.icon('arrow.up.right')}</button></div></nav>`;
  const story=`<article class="personal-story">${links}<header class="story-hero"><div><p class="story-eyebrow">EN QUELQUES MOTS</p><h1>Noa Giannone.<br>Développeur web & mobile.</h1><p class="story-intro">Je suis développeur à Marseille. Je travaille surtout sur des sites web et des applications mobiles, chez AirCarto et à mon compte.</p><a href="#story-code" class="story-scroll">Un peu plus sur moi ↓</a></div><figure><img src="images/profile-noa.jpeg" alt="Portrait de Noa Giannone"><figcaption>NOA GIANNONE · MARSEILLE</figcaption></figure></header>
    <section class="story-chapter" id="story-code"><div class="chapter-label"><span>01 / LE CODE</span><h2>Pourquoi<br>l’informatique ?</h2></div><div class="chapter-copy"><p>L’informatique m’intéresse depuis toujours. J’aime pouvoir partir d’une idée et la fabriquer moi-même. Il y a beaucoup d’essais, parfois des soirées entières sur un détail, mais voir quelqu’un utiliser ce que j’ai développé reste ma partie préférée.</p><p>Je passe une bonne partie de mon temps sur le front-end et les applications iOS et Android. J’aime autant dessiner le fonctionnement d’un écran que le développer : où placer une action, comment expliquer une information, ce qu’il se passe après un clic.</p><p>Quand je commence un projet personnel, je me demande à qui il pourrait servir. Whisp venait de la difficulté à rencontrer du monde à la fac. Avec Vago, je cherche à proposer une aide concrète pour les dépenses de carburant. Ce sont des sujets qui me concernent et sur lesquels j’ai envie de travailler.</p><button class="story-text-link" data-open-projects>Découvrir mes projets ↗</button></div></section>
    <section class="story-statement"><p>Ce que j’aime dans ce métier :<br><em>pouvoir fabriquer ce qui manque.</em></p><span>CE QUI GUIDE MON TRAVAIL</span></section>
    <section class="story-chapter"><div class="chapter-label"><span>02 / CONSTRUIRE</span><h2>Mon travail,<br>au quotidien.</h2></div><div class="chapter-copy"><p>Chez AirCarto, je travaille sur des capteurs de qualité de l’air. J’y ai découvert le firmware, développé en C++ pour des ESP et plongé dans le back-end, les données et le réseau. J’aime passer de l’écran à un objet qui mesure quelque chose dans le monde réel.</p><p>À côté, mon activité indépendante me donne une liberté à laquelle je tiens beaucoup. Je crée des sites, des applications et des plateformes métier : une programmation de festival, une billetterie, un outil pour une équipe… Des projets très concrets, avec des gens derrière.</p><p>Et puis il y a mes propres idées. Whisp, pour faciliter les rencontres entre étudiants. Vago, pour transformer du temps passé sur mobile en une aide pour le carburant. C’est là que je retrouve ce qui m’anime : partir d’un problème, et essayer d’apporter quelque chose.</p></div></section>
    <section class="story-travel"><div class="travel-heading"><div><span>03 / AILLEURS</span><h2>Quelques souvenirs<br>de voyage.</h2></div><p>J’aime voyager. Changer de décor, découvrir une ville à pied, repartir avec des images et des souvenirs qu’on n’aurait pas pu prévoir.</p></div><div class="travel-photos"><figure><img src="images/newyork.jpg" alt="Voyage à New York" loading="lazy"><figcaption>New York</figcaption></figure><figure><img src="images/vienne.jpg" alt="Voyage à Vienne" loading="lazy"><figcaption>Vienne</figcaption></figure><figure><img src="images/dubrovnik.jpg" alt="Voyage à Dubrovnik" loading="lazy"><figcaption>Dubrovnik</figcaption></figure></div><p class="travel-note">J’ai aussi découvert Lisbonne et Ténérife récemment. J’aime prendre le temps de me promener, changer mes habitudes quelques jours et rentrer avec de nouveaux souvenirs.</p></section>
    <section class="story-chapter airport-chapter"><div class="chapter-label"><span>04 / AVANT LE DÉPART</span><h2>Avant le décollage.</h2></div><div class="chapter-copy"><p>J’aime arriver à l’aéroport. Les annonces, le mouvement dans les terminaux, les avions qui se préparent au départ : cette agitation fait déjà partie du voyage. Dès que je peux, je m’installe près des vitres pour regarder les décollages.</p><p>Ce qui me plaît aussi, c’est de penser que chaque personne y vit un moment différent. Certains partent en vacances, d’autres rentrent chez eux ou vont retrouver quelqu’un. On se croise quelques minutes, chacun avec son histoire et sa destination.</p><p>Ma passion pour les avions est venue au fil de mes voyages. Aujourd’hui, je peux aller les regarder décoller simplement pour le plaisir. C’est un moment que je ne trouve jamais banal.</p></div></section>
    <footer class="story-footer"><span>NOA GIANNONE</span><h2>Vous avez un projet<br>à me raconter ?</h2><button data-contact>Parlons-en ${P.icon('arrow.up.right')}</button><small>Marseille · Toulon</small></footer></article>`;
  P.cvHTML=()=>`<article class="cv-live"><header><div><span class="cv-overline">CURRICULUM VITÆ</span><h1>${profile.name}</h1><h2>${profile.title}</h2><p>${profile.location} · ${profile.email}</p></div><img src="images/profile-noa.jpeg" alt="Noa Giannone"></header><p class="cv-summary">Développeur passionné par le front-end et les applications iOS et Android. Je conçois des interfaces soignées et des plateformes sur mesure. Mon expérience chez AirCarto étend cette pratique au firmware, aux données et aux infrastructures auto-hébergées.</p><div class="cv-columns"><main><h3>Expériences</h3>${profile.experiences.map(e=>`<section class="cv-experience"><div><h4>${e.role}</h4><span>${e.date}</span></div><h5>${e.company} · ${e.location}</h5><ul>${e.points.map(t=>`<li>${esc(t)}</li>`).join('')}</ul></section>`).join('')}<h3>Formation</h3>${profile.education.map(e=>`<section class="cv-experience"><div><h4>${e.title}</h4><span>${e.date}</span></div><h5>${e.school}</h5><p>${e.text}</p></section>`).join('')}</main><aside><h3>Compétences</h3>${profile.skills.map(s=>`<section><h4>${s.name}</h4><p>${s.items.join(' · ')}</p></section>`).join('')}<h3>Projets personnels</h3><p>Vago · Whisp · IA locale · ViteMonGrandOral</p><h3>Ce qui m’anime</h3><p>Créer des outils utiles.<br>Entreprendre et apprendre.<br>Voyager et découvrir l’aviation.</p></aside></div></article>`;
  function homeHTML(){return `<section class="safari-start"><h1>Favoris</h1><div class="safari-favorites"><button data-safari-page="histoire"><img src="images/profile-noa.jpeg" alt="">Mon histoire</button><button data-safari-page="cv"><img src="icon/apple/DocumentsFolderIcon.png" alt="">Mon CV</button><button data-open-projects><img src="icon/dock/finder.png" alt="">Mes projets</button><button data-contact><img src="icon/dock/mail.png" alt="">Me contacter</button></div><h2>À découvrir</h2><div class="safari-reading-list"><button data-safari-page="histoire"><img src="images/newyork.jpg" alt="New York"><span>En quelques mots<strong>Créer, voyager, recommencer.</strong><small>Mon histoire et ce qui m’anime.</small></span></button><button data-safari-page="cv"><img src="images/profile-noa.jpeg" alt="Noa"><span>Mon parcours<strong>Du front-end aux objets connectés.</strong><small>Expériences, compétences et projets.</small></span></button></div></section>`;}
  function render(){content.innerHTML=current==='histoire'?story:current==='cv'?`<div class="cv-browser-toolbar"><span>CV — Noa Giannone</span><a href="documents/CV-Noa-Giannone.pdf" download>Télécharger le PDF ${P.icon('square.and.arrow.down')}</a></div>${P.cvHTML()}`:homeHTML();document.querySelectorAll('[data-safari-page]').forEach(b=>{b.classList.toggle('selected',b.dataset.safariPage===current);if(b.getAttribute('role')==='tab')b.setAttribute('aria-selected',String(b.dataset.safariPage===current));});document.getElementById('safari-address').value=current==='home'?'Page de démarrage':`noagiannone.fr/${current==='cv'?'cv':'mon-histoire'}`;document.getElementById('safari-back').disabled=index===0;document.getElementById('safari-forward').disabled=index===history.length-1;content.scrollTop=0;}
  P.safariNavigate=page=>{if(!['home','histoire','cv'].includes(page)||page===current)return;history=history.slice(0,index+1);history.push(page);index++;current=page;render();};
  document.getElementById('win-safari').addEventListener('click',e=>{const tab=e.target.closest('[data-safari-page]');if(tab)P.safariNavigate(tab.dataset.safariPage);if(e.target.closest('[data-contact]')){P.open('mail');P.composeMail();}if(e.target.closest('[data-open-projects]'))P.open('finder');const jump=e.target.closest('a[href="#story-code"]');if(jump){e.preventDefault();content.querySelector('#story-code').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'auto':'smooth'});}});
  document.getElementById('safari-back').addEventListener('click',()=>{if(index>0){current=history[--index];render();}});document.getElementById('safari-forward').addEventListener('click',()=>{if(index<history.length-1){current=history[++index];render();}});document.getElementById('safari-refresh').addEventListener('click',render);
  document.getElementById('safari-sidebar-toggle').addEventListener('click',e=>{const sidebar=document.querySelector('.safari-native-sidebar');sidebar.hidden=!sidebar.hidden;e.currentTarget.setAttribute('aria-expanded',String(!sidebar.hidden));});
  document.getElementById('safari-address').addEventListener('keydown',e=>{if(e.key!=='Enter')return;const q=e.target.value.toLocaleLowerCase();if(/cv|parcours|compétence/.test(q))P.safariNavigate('cv');else if(/histoire|noa|moi/.test(q))P.safariNavigate('histoire');else if(/home|accueil|démarrage/.test(q))P.safariNavigate('home');else P.toast('Dans ce portfolio : recherchez « histoire », « CV » ou « accueil ».');});
  document.getElementById('safari-share').addEventListener('click',async()=>{const url=new URL(location.href);url.hash=current;try{await navigator.clipboard.writeText(url.href);P.toast('Lien copié.');}catch{P.toast('Copiez l’adresse depuis la barre de votre navigateur pour partager cette page.');}});
  if(['histoire','cv','home'].includes(location.hash.slice(1))){current=location.hash.slice(1);history=[current];}
  render();
  // The Notes CV and Safari CV consume the same profile so their content stays aligned.
  const noteBody=document.querySelector('.note-body');
  if(noteBody){noteBody.innerHTML=`<h1>Mon parcours</h1><p class="notes-intro">${profile.title}</p><div class="note-section"><h2>Expériences professionnelles</h2>${profile.experiences.map(e=>`<div class="experience-block"><h3>${e.role}</h3><span class="company">${e.company} · ${e.location}</span><span class="date">${e.date}</span><ul>${e.points.map(t=>`<li>${esc(t)}</li>`).join('')}</ul></div>`).join('')}</div><div class="note-section"><h2>Compétences</h2>${profile.skills.map(s=>`<div class="experience-block"><h3>${s.name}</h3><p>${s.items.join(' · ')}</p></div>`).join('')}</div><div class="note-section"><h2>Formation</h2>${profile.education.map(e=>`<div class="education-block"><h3>${e.title}</h3><span class="school">${e.school}</span><span class="date">${e.date}</span><p>${e.text}</p></div>`).join('')}</div><a class="native-button" href="documents/CV-Noa-Giannone.pdf" download>Télécharger mon CV</a>`;}
  const noteItems=document.querySelectorAll('.notes-items-list > li');
  noteItems.forEach((item,i)=>{if(i===1){item.querySelector('.note-item-title').textContent='Mes compétences';const preview=item.querySelector('.note-preview-text');if(preview)preview.textContent='Front-end, mobile, firmware et réseau';}item.addEventListener('click',()=>{noteItems.forEach(n=>n.classList.toggle('active',n===item));const target=i===1?noteBody.querySelectorAll('.note-section')[1]:noteBody;target?.scrollIntoView({block:'start'});});});
  const meta=document.querySelector('.note-date');if(meta)meta.textContent='Parcours & compétences';
});
